#:schema https://raw.githubusercontent.com/brycekbargar/dotfiles/main/precious-schema.json
[commands."common.EOF"]
type = "tidy"
include = ["*"]
exclude = ["*.feather", "*.parquet"]
cmd = ["end-of-file-fixer"]
ok_exit_codes = [0, 1]
[commands."common.whitespace"]
type = "tidy"
include = ["*"]
exclude = ["*.feather", "*.parquet"]
cmd = ["trailing-whitespace-fixer", "--markdown-linebreak-ext=md"]
ok_exit_codes = [0, 1]
[commands."common.large-files"]
type = "lint"
include = ["*"]
cmd = ["check-added-large-files"]
exclude = ["*.feather"]
ok_exit_codes = [0]
[commands."common.case"]
type = "lint"
include = ["*"]
cmd = ["check-case-conflict"]
exclude = ["*.feather"]
ok_exit_codes = [0]

[commands."quicklintjs.lint"]
type = "lint"
include = ["*.js"]
cmd = ["npx", "--no", "quick-lint-js"]
working_dir.chdir-to = "site"
ok_exit_codes = [0]
[commands."prettier.format"]
type = "both"
include = ["*.js", "*.html"]
cmd = ["npx", "--no", "prettier"]
working_dir.chdir-to = "site"
lint_flags = ["--check"]
tidy_flags = ["--write"]
ok_exit_codes = [0]

[commands."ruff.lint"]
type = "both"
include = ["*.py"]
cmd = ["ruff", "check", "--quiet"]
tidy_flags = ["--fix-only"]
ok_exit_codes = [0]
[commands."ruff.format"]
type = "both"
include = ["*.py"]
cmd = ["ruff", "format", "--quiet"]
lint_flags = ["--diff"]
ok_exit_codes = [0]
